### ISSUE TITLE
First release roadmap

### ISSUE THREAD

**Issue by allavr** [crispyeuro/crispyeuro-client#1]
# First release roadmap 
### Guest user interface
- [x] Add Login page. 
- [x] Add Sign-up tab.
- [x] Add Forgot Password tab.
- [x] Add Terms of Use tab.
#### Top navigation tabs
- [x] Add Top navigation. Top navigation includes buttons: Logo, Messages, Swap, Settings, Log out.
- [x] Add Messages tab. Messages tab includes messages from another users and Search sub-tab.
- [x] Add Search sub tab. It represents a search for other users to add them to Contacts list.
- [x] Add Swap tab. Swap tab includes swap offers form another users and user's offers.
- [x] Add Settings tab. Settings tab includes user account settings.
#### Side navigation tabs
- [x] Add Side navigation. Side navigation includes Statistics bar, links: Statistics, Issues plan, Categories, Countries, Denominations, Commemorative, Colorized coins, Silver coins, Gold coins.
- [x] Add statistics bar. Statistic bar represents a number and percentage of all added coins.
- [x] Add statistics tab. It includes A pie chart, which represents added coins by categories.
- [x] Add issues plan tab. It includes a table of future coin issues by country. 
##### Coin categories tab
- [x] Add Coin categories tab. Categories tab includes sub-categories: Countries, Denominations, Commemorative, Colorized coins, Silver coins, Gold coins.
- [x] Add Country tab. Country tab is a template for every country. It includes Description, Coins categories: Ordinary, Commemorative 2 euro, Other denominations, Silver coins, Gold coins.
- [x] Add Denomination tab. Denomination tab is a template for every denomination. In includes Description, Coins table by countries
- [x] Add Year template tab. Year tab is a template for Commemorative 2 euro coins, Colorized coins, Silver coins, Gold coins sorted by specific year.
- [x] Add Country template tab. Country tab is a template for Commemorative 2 euro coins, Colorized coins, Silver coins, Gold coins sorted by specific country.
#### Coin tab
- [x] Add Coin tab. Coin tab is a template for every euro coin. It includes Specification: table and coin picture, Mintage table, My collection sub-tab, Swap availability sub-tab.
- [x] Add My collection sub-tab. It includes an Add coin tab and table of added coin issues.
- [x] Add Add coin tab. Add coin form. When coin added, it is showed in a specific Coin tab in My collection sub-tab.
- [x] Add Swap availability sub-tab. It includes other user's offers, and user's settings for a specific coin to be available for swap.
